server:
  port: 8888
spring:  cloud:    config:      server:        git:          uri: http://localhost:3000/springcloud/spring-cloud-config.git
          username: springcloud
          password: 123456  application:    name: config-server  rabbitmq:    host: localhost
    port: 5672
    username: guest
    password: guest